### ISSUE TITLE
IndicatorView is not visible only on iPhone 5 

### ISSUE THREAD

**Issue by tungfam** [ninjaprox/NVActivityIndicatorView#138] opened 2017-04-03 20:41 UTC
Encountered an issue that the IndicatorView is not visible on the iPhone 5.

I created a clean project and here is my code: 

```swift
var loader: NVActivityIndicatorView?

override func viewDidLoad() {
        super.viewDidLoad()

        loader = NVActivityIndicatorView(frame: CGRect(x: self.view.center.x - 20,
                                                            y: self.view.center.y + 70,
                                                            width: CGFloat(40),
                                                            height: CGFloat(40)),
                                              type: .ballGridPulse ,
                                              color: UIColor.red,
                                              padding: CGFloat(0.0))
        view.addSubview(loader!)
        loader?.startAnimating()
```

The indicator is visible on any iPhone except iPhone 5 (not sure about 4s)

EDIT: details: when i open the view debugger i DO see the 'box' with the loader. but it's just invisible. not white color. i this it's clear color.. but doing `po loader.color` returns correct color..

**Comment by tungfam** [comment] 2017-04-03 20:51
> **image of view debugger:** 

<img width="907" alt="123" src="https://cloud.githubusercontent.com/assets/17186720/24631180/128da0e6-18c8-11e7-948f-cf4d6f9fc8e9.png">

> **the color of loader:**

![image](https://cloud.githubusercontent.com/assets/17186720/24631284/67cfe1e0-18c8-11e7-881f-9affaa62dc68.png)

**Comment by ninjaprox** [comment] 2017-04-04 13:13
@tungfam: Thanks for reporting 👍. Confirm this issue on iPhone 5 (5s is fine). I tried running the demo project on iPhone 5 10.3 simulator and got the same thing you reported here. However some of animations don't have this issue, you can open the demo to see what works and not. In the meantime, I suggest using working ones, I'll be looking into this issue, update later then.

**Comment by shady-gabal** [comment] 2017-04-04 14:51
Looks like this happened somewhere in the conversion to Swift 3. Can use the Swift 2.3 branch (and manually convert to Swift 3 if needed by going to Editor -> Convert -> Current Swift), and this bug does not appear.

**Comment by tungfam** [comment] 2017-04-04 21:20
Got it, thanks.

Pointing to 3.5.2 also solves the issue:
`pod 'NVActivityIndicatorView’, ‘3.5.2’`

**Comment by ninjaprox** [comment] 2017-04-14 14:35
@tungfam: `3.6.1` is out with the fix for this 🚀. Thanks @shady-gabal for helping figure out the cause.

**Closed as completed by ninjaprox** 2017-04-14 14:35 UTC
Labels: bug, help wanted
