### ISSUE TITLE
Add NV as subview when stopAnimating to present alertVC all fail

### ISSUE THREAD

**Issue by lucasjinreal** [ninjaprox/NVActivityIndicatorView#93] opened 2016-11-14 09:31 UTC
stop animating of NV, and call to present alertVC, it won't present automatically except user touch the screen again, anyone know why?
```
activityIndicatorView.stopAnimating()
activityIndicatorView.removeFromSuperview()
let alertvc = UIAlertController(title: "学号或密码错误", message: "校外人员无法登陆", preferredStyle: .alert)
let action = UIAlertAction(title: "确定", style: .default, handler: nil)
alertvc.addAction(action)
self.present(alertvc, animated: true, completion: nil)
```

**Comment by ninjaprox** [comment] 2016-11-15 13:32
@jinfagang: Please elaborate on this. It seems the issue isn't because of `NVActivityIndicatorView`.

**Comment by ninjaprox** [comment] 2016-12-04 10:23
Close this, reopen if need be.

**Closed as completed by ninjaprox** 2016-12-04 10:23 UTC
