### ISSUE TITLE
Animation start delay

### ISSUE THREAD

**Issue by keba76** [ninjaprox/NVActivityIndicatorView#164] opened 2017-09-12 13:58 UTC
There was such a problem, each time with a re-animation, there is a slight delay in the animation. And with each time this time delay increases. A picture of the animation appears immediately, but the animation itself works through time. At the first start there is no delay.
I would be grateful for your help

**Comment by ninjaprox** [comment] 2017-09-18 14:59
@keba76: Sorry for delay reply. Could you give the code example of your use case? It'll help debug this. I tried to replicate this by modifying the example project as below:
```swift
class MyButton: UIButton {
    weak var indicatorView: NVActivityIndicatorView!
}

// In ViewController
override func viewDidLoad() {
    // ...
    let button = MyButton(frame: frame)
    button.tag = $0
    button.addTarget(self,
        action: #selector(buttonTapped(_:)),
        for: UIControlEvents.touchUpInside)
    button.indicatorView = activityIndicatorView
    self.view.addSubview(button)
}

func buttonTapped(_ sender: MyButton) {
    let activityIndicatorView = sender.indicatorView!
    if activityIndicatorView.isAnimating {
        activityIndicatorView.stopAnimating()
    } else {
        activityIndicatorView.startAnimating()
    }
}
```

However, it seems to be not enough to reproduce the issue.

**Comment by ninjaprox** [comment] 2017-10-31 14:22
Close this, reopen if need be.

**Closed as completed by ninjaprox** 2017-10-31 14:22 UTC
